namespace Slack.Webhooks
{
	public static class Emoji
	{
		public static string PlusOne { get { return ":+1:"; } }
		public static string MinusOne { get { return ":-1:"; } }
		public static string OneHundred { get { return ":100:"; } }
		public static string OneTwoThreeFour { get { return ":1234:"; } }
		public static string EightBall { get { return ":8ball:"; } }
		public static string A { get { return ":a:"; } }
		public static string Ab { get { return ":ab:"; } }
		public static string Abc { get { return ":abc:"; } }
		public static string Abcd { get { return ":abcd:"; } }
		public static string Accept { get { return ":accept:"; } }
		public static string Aerial_tramway { get { return ":aerial_tramway:"; } }
		public static string Airplane { get { return ":airplane:"; } }
		public static string Alarm_clock { get { return ":alarm_clock:"; } }
		public static string Alien { get { return ":alien:"; } }
		public static string Ambulance { get { return ":ambulance:"; } }
		public static string Anchor { get { return ":anchor:"; } }
		public static string Angel { get { return ":angel:"; } }
		public static string Anger { get { return ":anger:"; } }
		public static string Angry { get { return ":angry:"; } }
		public static string Anguished { get { return ":anguished:"; } }
		public static string Ant { get { return ":ant:"; } }
		public static string Apple { get { return ":apple:"; } }
		public static string Aquarius { get { return ":aquarius:"; } }
		public static string Aries { get { return ":aries:"; } }
		public static string Arrow_backward { get { return ":arrow_backward:"; } }
		public static string Arrow_double_down { get { return ":arrow_double_down:"; } }
		public static string Arrow_double_up { get { return ":arrow_double_up:"; } }
		public static string Arrow_down { get { return ":arrow_down:"; } }
		public static string Arrow_down_small { get { return ":arrow_down_small:"; } }
		public static string Arrow_forward { get { return ":arrow_forward:"; } }
		public static string Arrow_heading_down { get { return ":arrow_heading_down:"; } }
		public static string Arrow_heading_up { get { return ":arrow_heading_up:"; } }
		public static string Arrow_left { get { return ":arrow_left:"; } }
		public static string Arrow_lower_left { get { return ":arrow_lower_left:"; } }
		public static string Arrow_lower_right { get { return ":arrow_lower_right:"; } }
		public static string Arrow_right { get { return ":arrow_right:"; } }
		public static string Arrow_right_hook { get { return ":arrow_right_hook:"; } }
		public static string Arrow_up { get { return ":arrow_up:"; } }
		public static string Arrow_up_down { get { return ":arrow_up_down:"; } }
		public static string Arrow_up_small { get { return ":arrow_up_small:"; } }
		public static string Arrow_upper_left { get { return ":arrow_upper_left:"; } }
		public static string Arrow_upper_right { get { return ":arrow_upper_right:"; } }
		public static string Arrows_clockwise { get { return ":arrows_clockwise:"; } }
		public static string Arrows_counterclockwise { get { return ":arrows_counterclockwise:"; } }
		public static string Art { get { return ":art:"; } }
		public static string Articulated_lorry { get { return ":articulated_lorry:"; } }
		public static string Astonished { get { return ":astonished:"; } }
		public static string Atm { get { return ":atm:"; } }
		public static string B { get { return ":b:"; } }
		public static string Baby { get { return ":baby:"; } }
		public static string Baby_bottle { get { return ":baby_bottle:"; } }
		public static string Baby_chick { get { return ":baby_chick:"; } }
		public static string Baby_symbol { get { return ":baby_symbol:"; } }
		public static string Back { get { return ":back:"; } }
		public static string Baggage_claim { get { return ":baggage_claim:"; } }
		public static string Balloon { get { return ":balloon:"; } }
		public static string Ballot_box_with_check { get { return ":ballot_box_with_check:"; } }
		public static string Bamboo { get { return ":bamboo:"; } }
		public static string Banana { get { return ":banana:"; } }
		public static string Bangbang { get { return ":bangbang:"; } }
		public static string Bank { get { return ":bank:"; } }
		public static string Bar_chart { get { return ":bar_chart:"; } }
		public static string Barber { get { return ":barber:"; } }
		public static string Baseball { get { return ":baseball:"; } }
		public static string Basketball { get { return ":basketball:"; } }
		public static string Bath { get { return ":bath:"; } }
		public static string Bathtub { get { return ":bathtub:"; } }
		public static string Battery { get { return ":battery:"; } }
		public static string Bear { get { return ":bear:"; } }
		public static string Bee { get { return ":bee:"; } }
		public static string Beer { get { return ":beer:"; } }
		public static string Beers { get { return ":beers:"; } }
		public static string Beetle { get { return ":beetle:"; } }
		public static string Beginner { get { return ":beginner:"; } }
		public static string Bell { get { return ":bell:"; } }
		public static string Bento { get { return ":bento:"; } }
		public static string Bicyclist { get { return ":bicyclist:"; } }
		public static string Bike { get { return ":bike:"; } }
		public static string Bikini { get { return ":bikini:"; } }
		public static string Bird { get { return ":bird:"; } }
		public static string Birthday { get { return ":birthday:"; } }
		public static string Black_circle { get { return ":black_circle:"; } }
		public static string Black_joker { get { return ":black_joker:"; } }
		public static string Black_medium_small_square { get { return ":black_medium_small_square:"; } }
		public static string Black_medium_square { get { return ":black_medium_square:"; } }
		public static string Black_nib { get { return ":black_nib:"; } }
		public static string Black_small_square { get { return ":black_small_square:"; } }
		public static string Black_square { get { return ":black_square:"; } }
		public static string Black_square_button { get { return ":black_square_button:"; } }
		public static string Blossom { get { return ":blossom:"; } }
		public static string Blowfish { get { return ":blowfish:"; } }
		public static string Blue_book { get { return ":blue_book:"; } }
		public static string Blue_car { get { return ":blue_car:"; } }
		public static string Blue_heart { get { return ":blue_heart:"; } }
		public static string Blush { get { return ":blush:"; } }
		public static string Boar { get { return ":boar:"; } }
		public static string Boat { get { return ":boat:"; } }
		public static string Bomb { get { return ":bomb:"; } }
		public static string Book { get { return ":book:"; } }
		public static string Bookmark { get { return ":bookmark:"; } }
		public static string Bookmark_tabs { get { return ":bookmark_tabs:"; } }
		public static string Books { get { return ":books:"; } }
		public static string Boom { get { return ":boom:"; } }
		public static string Boot { get { return ":boot:"; } }
		public static string Bouquet { get { return ":bouquet:"; } }
		public static string Bow { get { return ":bow:"; } }
		public static string Bowling { get { return ":bowling:"; } }
		public static string Bowtie { get { return ":bowtie:"; } }
		public static string Boy { get { return ":boy:"; } }
		public static string Bread { get { return ":bread:"; } }
		public static string Bride_with_veil { get { return ":bride_with_veil:"; } }
		public static string Bridge_at_night { get { return ":bridge_at_night:"; } }
		public static string Briefcase { get { return ":briefcase:"; } }
		public static string Broken_heart { get { return ":broken_heart:"; } }
		public static string Bug { get { return ":bug:"; } }
		public static string Bulb { get { return ":bulb:"; } }
		public static string Bullettrain_front { get { return ":bullettrain_front:"; } }
		public static string Bullettrain_side { get { return ":bullettrain_side:"; } }
		public static string Bus { get { return ":bus:"; } }
		public static string Busstop { get { return ":busstop:"; } }
		public static string Bust_in_silhouette { get { return ":bust_in_silhouette:"; } }
		public static string Busts_in_silhouette { get { return ":busts_in_silhouette:"; } }
		public static string Cactus { get { return ":cactus:"; } }
		public static string Cake { get { return ":cake:"; } }
		public static string Calendar { get { return ":calendar:"; } }
		public static string Calling { get { return ":calling:"; } }
		public static string Camel { get { return ":camel:"; } }
		public static string Camera { get { return ":camera:"; } }
		public static string Cancer { get { return ":cancer:"; } }
		public static string Candy { get { return ":candy:"; } }
		public static string Capital_abcd { get { return ":capital_abcd:"; } }
		public static string Capricorn { get { return ":capricorn:"; } }
		public static string Car { get { return ":car:"; } }
		public static string Card_index { get { return ":card_index:"; } }
		public static string Carousel_horse { get { return ":carousel_horse:"; } }
		public static string Cat { get { return ":cat:"; } }
		public static string Cat2 { get { return ":cat2:"; } }
		public static string Cd { get { return ":cd:"; } }
		public static string Chart { get { return ":chart:"; } }
		public static string Chart_with_downwards_trend { get { return ":chart_with_downwards_trend:"; } }
		public static string Chart_with_upwards_trend { get { return ":chart_with_upwards_trend:"; } }
		public static string Checkered_flag { get { return ":checkered_flag:"; } }
		public static string Cherries { get { return ":cherries:"; } }
		public static string Cherry_blossom { get { return ":cherry_blossom:"; } }
		public static string Chestnut { get { return ":chestnut:"; } }
		public static string Chicken { get { return ":chicken:"; } }
		public static string Children_crossing { get { return ":children_crossing:"; } }
		public static string Chocolate_bar { get { return ":chocolate_bar:"; } }
		public static string Christmas_tree { get { return ":christmas_tree:"; } }
		public static string Church { get { return ":church:"; } }
		public static string Cinema { get { return ":cinema:"; } }
		public static string Circus_tent { get { return ":circus_tent:"; } }
		public static string City_sunrise { get { return ":city_sunrise:"; } }
		public static string City_sunset { get { return ":city_sunset:"; } }
		public static string Cl { get { return ":cl:"; } }
		public static string Clap { get { return ":clap:"; } }
		public static string Clapper { get { return ":clapper:"; } }
		public static string Clipboard { get { return ":clipboard:"; } }
		public static string Clock1 { get { return ":clock1:"; } }
		public static string Clock10 { get { return ":clock10:"; } }
		public static string Clock1030 { get { return ":clock1030:"; } }
		public static string Clock11 { get { return ":clock11:"; } }
		public static string Clock1130 { get { return ":clock1130:"; } }
		public static string Clock12 { get { return ":clock12:"; } }
		public static string Clock1230 { get { return ":clock1230:"; } }
		public static string Clock130 { get { return ":clock130:"; } }
		public static string Clock2 { get { return ":clock2:"; } }
		public static string Clock230 { get { return ":clock230:"; } }
		public static string Clock3 { get { return ":clock3:"; } }
		public static string Clock330 { get { return ":clock330:"; } }
		public static string Clock4 { get { return ":clock4:"; } }
		public static string Clock430 { get { return ":clock430:"; } }
		public static string Clock5 { get { return ":clock5:"; } }
		public static string Clock530 { get { return ":clock530:"; } }
		public static string Clock6 { get { return ":clock6:"; } }
		public static string Clock630 { get { return ":clock630:"; } }
		public static string Clock7 { get { return ":clock7:"; } }
		public static string Clock730 { get { return ":clock730:"; } }
		public static string Clock8 { get { return ":clock8:"; } }
		public static string Clock830 { get { return ":clock830:"; } }
		public static string Clock9 { get { return ":clock9:"; } }
		public static string Clock930 { get { return ":clock930:"; } }
		public static string Closed_book { get { return ":closed_book:"; } }
		public static string Closed_lock_with_key { get { return ":closed_lock_with_key:"; } }
		public static string Closed_umbrella { get { return ":closed_umbrella:"; } }
		public static string Cloud { get { return ":cloud:"; } }
		public static string Clubs { get { return ":clubs:"; } }
		public static string Cn { get { return ":cn:"; } }
		public static string Cocktail { get { return ":cocktail:"; } }
		public static string Coffee { get { return ":coffee:"; } }
		public static string Cold_sweat { get { return ":cold_sweat:"; } }
		public static string Collision { get { return ":collision:"; } }
		public static string Computer { get { return ":computer:"; } }
		public static string Confetti_ball { get { return ":confetti_ball:"; } }
		public static string Confounded { get { return ":confounded:"; } }
		public static string Confused { get { return ":confused:"; } }
		public static string Congratulations { get { return ":congratulations:"; } }
		public static string Construction { get { return ":construction:"; } }
		public static string Construction_worker { get { return ":construction_worker:"; } }
		public static string Convenience_store { get { return ":convenience_store:"; } }
		public static string Cookie { get { return ":cookie:"; } }
		public static string Cool { get { return ":cool:"; } }
		public static string Cop { get { return ":cop:"; } }
		public static string Copyright { get { return ":copyright:"; } }
		public static string Corn { get { return ":corn:"; } }
		public static string Couple { get { return ":couple:"; } }
		public static string Couple_with_heart { get { return ":couple_with_heart:"; } }
		public static string Couplekiss { get { return ":couplekiss:"; } }
		public static string Cow { get { return ":cow:"; } }
		public static string Cow2 { get { return ":cow2:"; } }
		public static string Credit_card { get { return ":credit_card:"; } }
		public static string Crocodile { get { return ":crocodile:"; } }
		public static string Crossed_flags { get { return ":crossed_flags:"; } }
		public static string Crown { get { return ":crown:"; } }
		public static string Cry { get { return ":cry:"; } }
		public static string Crying_cat_face { get { return ":crying_cat_face:"; } }
		public static string Crystal_ball { get { return ":crystal_ball:"; } }
		public static string Cupid { get { return ":cupid:"; } }
		public static string Curly_loop { get { return ":curly_loop:"; } }
		public static string Currency_exchange { get { return ":currency_exchange:"; } }
		public static string Curry { get { return ":curry:"; } }
		public static string Custard { get { return ":custard:"; } }
		public static string Customs { get { return ":customs:"; } }
		public static string Cyclone { get { return ":cyclone:"; } }
		public static string Dancer { get { return ":dancer:"; } }
		public static string Dancers { get { return ":dancers:"; } }
		public static string Dango { get { return ":dango:"; } }
		public static string Dart { get { return ":dart:"; } }
		public static string Dash { get { return ":dash:"; } }
		public static string Date { get { return ":date:"; } }
		public static string De { get { return ":de:"; } }
		public static string Deciduous_tree { get { return ":deciduous_tree:"; } }
		public static string Department_store { get { return ":department_store:"; } }
		public static string Diamond_shape_with_a_dot_inside { get { return ":diamond_shape_with_a_dot_inside:"; } }
		public static string Diamonds { get { return ":diamonds:"; } }
		public static string Disappointed { get { return ":disappointed:"; } }
		public static string Disappointed_relieved { get { return ":disappointed_relieved:"; } }
		public static string Dizzy { get { return ":dizzy:"; } }
		public static string Dizzy_face { get { return ":dizzy_face:"; } }
		public static string Do_not_litter { get { return ":do_not_litter:"; } }
		public static string Dog { get { return ":dog:"; } }
		public static string Dog2 { get { return ":dog2:"; } }
		public static string Dollar { get { return ":dollar:"; } }
		public static string Dolls { get { return ":dolls:"; } }
		public static string Dolphin { get { return ":dolphin:"; } }
		public static string Donut { get { return ":donut:"; } }
		public static string Door { get { return ":door:"; } }
		public static string Doughnut { get { return ":doughnut:"; } }
		public static string Dragon { get { return ":dragon:"; } }
		public static string Dragon_face { get { return ":dragon_face:"; } }
		public static string Dress { get { return ":dress:"; } }
		public static string Dromedary_camel { get { return ":dromedary_camel:"; } }
		public static string Droplet { get { return ":droplet:"; } }
		public static string Dvd { get { return ":dvd:"; } }
		public static string Ehyphenmail { get { return ":e-mail:"; } }
		public static string Ear { get { return ":ear:"; } }
		public static string Ear_of_rice { get { return ":ear_of_rice:"; } }
		public static string Earth_africa { get { return ":earth_africa:"; } }
		public static string Earth_americas { get { return ":earth_americas:"; } }
		public static string Earth_asia { get { return ":earth_asia:"; } }
		public static string Egg { get { return ":egg:"; } }
		public static string Eggplant { get { return ":eggplant:"; } }
		public static string Eight { get { return ":eight:"; } }
		public static string Eight_pointed_black_star { get { return ":eight_pointed_black_star:"; } }
		public static string Eight_spoked_asterisk { get { return ":eight_spoked_asterisk:"; } }
		public static string Electric_plug { get { return ":electric_plug:"; } }
		public static string Elephant { get { return ":elephant:"; } }
		public static string Email { get { return ":email:"; } }
		public static string End { get { return ":end:"; } }
		public static string Envelope { get { return ":envelope:"; } }
		public static string Es { get { return ":es:"; } }
		public static string Euro { get { return ":euro:"; } }
		public static string European_castle { get { return ":european_castle:"; } }
		public static string European_post_office { get { return ":european_post_office:"; } }
		public static string Evergreen_tree { get { return ":evergreen_tree:"; } }
		public static string Exclamation { get { return ":exclamation:"; } }
		public static string Expressionless { get { return ":expressionless:"; } }
		public static string Eyeglasses { get { return ":eyeglasses:"; } }
		public static string Eyes { get { return ":eyes:"; } }
		public static string Facepunch { get { return ":facepunch:"; } }
		public static string Factory { get { return ":factory:"; } }
		public static string Fallen_leaf { get { return ":fallen_leaf:"; } }
		public static string Family { get { return ":family:"; } }
		public static string Fast_forward { get { return ":fast_forward:"; } }
		public static string Fax { get { return ":fax:"; } }
		public static string Fearful { get { return ":fearful:"; } }
		public static string Feelsgood { get { return ":feelsgood:"; } }
		public static string Feet { get { return ":feet:"; } }
		public static string Ferris_wheel { get { return ":ferris_wheel:"; } }
		public static string File_folder { get { return ":file_folder:"; } }
		public static string Finnadie { get { return ":finnadie:"; } }
		public static string Fire { get { return ":fire:"; } }
		public static string Fire_engine { get { return ":fire_engine:"; } }
		public static string Fireworks { get { return ":fireworks:"; } }
		public static string First_quarter_moon { get { return ":first_quarter_moon:"; } }
		public static string First_quarter_moon_with_face { get { return ":first_quarter_moon_with_face:"; } }
		public static string Fish { get { return ":fish:"; } }
		public static string Fish_cake { get { return ":fish_cake:"; } }
		public static string Fishing_pole_and_fish { get { return ":fishing_pole_and_fish:"; } }
		public static string Fist { get { return ":fist:"; } }
		public static string Five { get { return ":five:"; } }
		public static string Flags { get { return ":flags:"; } }
		public static string Flashlight { get { return ":flashlight:"; } }
		public static string Floppy_disk { get { return ":floppy_disk:"; } }
		public static string Flower_playing_cards { get { return ":flower_playing_cards:"; } }
		public static string Flushed { get { return ":flushed:"; } }
		public static string Foggy { get { return ":foggy:"; } }
		public static string Football { get { return ":football:"; } }
		public static string Fork_and_knife { get { return ":fork_and_knife:"; } }
		public static string Fountain { get { return ":fountain:"; } }
		public static string Four { get { return ":four:"; } }
		public static string Four_leaf_clover { get { return ":four_leaf_clover:"; } }
		public static string Fr { get { return ":fr:"; } }
		public static string Free { get { return ":free:"; } }
		public static string Fried_shrimp { get { return ":fried_shrimp:"; } }
		public static string Fries { get { return ":fries:"; } }
		public static string Frog { get { return ":frog:"; } }
		public static string Frowning { get { return ":frowning:"; } }
		public static string Fu { get { return ":fu:"; } }
		public static string Fuelpump { get { return ":fuelpump:"; } }
		public static string Full_moon { get { return ":full_moon:"; } }
		public static string Full_moon_with_face { get { return ":full_moon_with_face:"; } }
		public static string Game_die { get { return ":game_die:"; } }
		public static string Gb { get { return ":gb:"; } }
		public static string Gem { get { return ":gem:"; } }
		public static string Gemini { get { return ":gemini:"; } }
		public static string Ghost { get { return ":ghost:"; } }
		public static string Gift { get { return ":gift:"; } }
		public static string Gift_heart { get { return ":gift_heart:"; } }
		public static string Girl { get { return ":girl:"; } }
		public static string Globe_with_meridians { get { return ":globe_with_meridians:"; } }
		public static string Goat { get { return ":goat:"; } }
		public static string Goberserk { get { return ":goberserk:"; } }
		public static string Godmode { get { return ":godmode:"; } }
		public static string Golf { get { return ":golf:"; } }
		public static string Grapes { get { return ":grapes:"; } }
		public static string Green_apple { get { return ":green_apple:"; } }
		public static string Green_book { get { return ":green_book:"; } }
		public static string Green_heart { get { return ":green_heart:"; } }
		public static string Grey_exclamation { get { return ":grey_exclamation:"; } }
		public static string Grey_question { get { return ":grey_question:"; } }
		public static string Grimacing { get { return ":grimacing:"; } }
		public static string Grin { get { return ":grin:"; } }
		public static string Grinning { get { return ":grinning:"; } }
		public static string Guardsman { get { return ":guardsman:"; } }
		public static string Guitar { get { return ":guitar:"; } }
		public static string Gun { get { return ":gun:"; } }
		public static string Haircut { get { return ":haircut:"; } }
		public static string Hamburger { get { return ":hamburger:"; } }
		public static string Hammer { get { return ":hammer:"; } }
		public static string Hamster { get { return ":hamster:"; } }
		public static string Hand { get { return ":hand:"; } }
		public static string Handbag { get { return ":handbag:"; } }
		public static string Hankey { get { return ":hankey:"; } }
		public static string Hash { get { return ":hash:"; } }
		public static string Hatched_chick { get { return ":hatched_chick:"; } }
		public static string Hatching_chick { get { return ":hatching_chick:"; } }
		public static string Headphones { get { return ":headphones:"; } }
		public static string Hear_no_evil { get { return ":hear_no_evil:"; } }
		public static string Heart { get { return ":heart:"; } }
		public static string Heart_decoration { get { return ":heart_decoration:"; } }
		public static string Heart_eyes { get { return ":heart_eyes:"; } }
		public static string Heart_eyes_cat { get { return ":heart_eyes_cat:"; } }
		public static string Heartbeat { get { return ":heartbeat:"; } }
		public static string Heartpulse { get { return ":heartpulse:"; } }
		public static string Hearts { get { return ":hearts:"; } }
		public static string Heavy_check_mark { get { return ":heavy_check_mark:"; } }
		public static string Heavy_division_sign { get { return ":heavy_division_sign:"; } }
		public static string Heavy_dollar_sign { get { return ":heavy_dollar_sign:"; } }
		public static string Heavy_exclamation_mark { get { return ":heavy_exclamation_mark:"; } }
		public static string Heavy_minus_sign { get { return ":heavy_minus_sign:"; } }
		public static string Heavy_multiplication_x { get { return ":heavy_multiplication_x:"; } }
		public static string Heavy_plus_sign { get { return ":heavy_plus_sign:"; } }
		public static string Helicopter { get { return ":helicopter:"; } }
		public static string Herb { get { return ":herb:"; } }
		public static string Hibiscus { get { return ":hibiscus:"; } }
		public static string High_brightness { get { return ":high_brightness:"; } }
		public static string High_heel { get { return ":high_heel:"; } }
		public static string Hocho { get { return ":hocho:"; } }
		public static string Honey_pot { get { return ":honey_pot:"; } }
		public static string Honeybee { get { return ":honeybee:"; } }
		public static string Horse { get { return ":horse:"; } }
		public static string Horse_racing { get { return ":horse_racing:"; } }
		public static string Hospital { get { return ":hospital:"; } }
		public static string Hotel { get { return ":hotel:"; } }
		public static string Hotsprings { get { return ":hotsprings:"; } }
		public static string Hourglass { get { return ":hourglass:"; } }
		public static string Hourglass_flowing_sand { get { return ":hourglass_flowing_sand:"; } }
		public static string House { get { return ":house:"; } }
		public static string House_with_garden { get { return ":house_with_garden:"; } }
		public static string Hurtrealbad { get { return ":hurtrealbad:"; } }
		public static string Hushed { get { return ":hushed:"; } }
		public static string Ice_cream { get { return ":ice_cream:"; } }
		public static string Icecream { get { return ":icecream:"; } }
		public static string Id { get { return ":id:"; } }
		public static string Ideograph_advantage { get { return ":ideograph_advantage:"; } }
		public static string Imp { get { return ":imp:"; } }
		public static string Inbox_tray { get { return ":inbox_tray:"; } }
		public static string Incoming_envelope { get { return ":incoming_envelope:"; } }
		public static string Information_desk_person { get { return ":information_desk_person:"; } }
		public static string Information_source { get { return ":information_source:"; } }
		public static string Innocent { get { return ":innocent:"; } }
		public static string Interrobang { get { return ":interrobang:"; } }
		public static string Iphone { get { return ":iphone:"; } }
		public static string It { get { return ":it:"; } }
		public static string Izakaya_lantern { get { return ":izakaya_lantern:"; } }
		public static string Jack_o_lantern { get { return ":jack_o_lantern:"; } }
		public static string Japan { get { return ":japan:"; } }
		public static string Japanese_castle { get { return ":japanese_castle:"; } }
		public static string Japanese_goblin { get { return ":japanese_goblin:"; } }
		public static string Japanese_ogre { get { return ":japanese_ogre:"; } }
		public static string Jeans { get { return ":jeans:"; } }
		public static string Joy { get { return ":joy:"; } }
		public static string Joy_cat { get { return ":joy_cat:"; } }
		public static string Jp { get { return ":jp:"; } }
		public static string Key { get { return ":key:"; } }
		public static string Keycap_ten { get { return ":keycap_ten:"; } }
		public static string Kimono { get { return ":kimono:"; } }
		public static string Kiss { get { return ":kiss:"; } }
		public static string Kissing { get { return ":kissing:"; } }
		public static string Kissing_cat { get { return ":kissing_cat:"; } }
		public static string Kissing_closed_eyes { get { return ":kissing_closed_eyes:"; } }
		public static string Kissing_face { get { return ":kissing_face:"; } }
		public static string Kissing_heart { get { return ":kissing_heart:"; } }
		public static string Kissing_smiling_eyes { get { return ":kissing_smiling_eyes:"; } }
		public static string Koala { get { return ":koala:"; } }
		public static string Koko { get { return ":koko:"; } }
		public static string Kr { get { return ":kr:"; } }
		public static string Large_blue_circle { get { return ":large_blue_circle:"; } }
		public static string Large_blue_diamond { get { return ":large_blue_diamond:"; } }
		public static string Large_orange_diamond { get { return ":large_orange_diamond:"; } }
		public static string Last_quarter_moon { get { return ":last_quarter_moon:"; } }
		public static string Last_quarter_moon_with_face { get { return ":last_quarter_moon_with_face:"; } }
		public static string Laughing { get { return ":laughing:"; } }
		public static string Leaves { get { return ":leaves:"; } }
		public static string Ledger { get { return ":ledger:"; } }
		public static string Left_luggage { get { return ":left_luggage:"; } }
		public static string Left_right_arrow { get { return ":left_right_arrow:"; } }
		public static string Leftwards_arrow_with_hook { get { return ":leftwards_arrow_with_hook:"; } }
		public static string Lemon { get { return ":lemon:"; } }
		public static string Leo { get { return ":leo:"; } }
		public static string Leopard { get { return ":leopard:"; } }
		public static string Libra { get { return ":libra:"; } }
		public static string Light_rail { get { return ":light_rail:"; } }
		public static string Link { get { return ":link:"; } }
		public static string Lips { get { return ":lips:"; } }
		public static string Lipstick { get { return ":lipstick:"; } }
		public static string Lock { get { return ":lock:"; } }
		public static string Lock_with_ink_pen { get { return ":lock_with_ink_pen:"; } }
		public static string Lollipop { get { return ":lollipop:"; } }
		public static string Loop { get { return ":loop:"; } }
		public static string Loudspeaker { get { return ":loudspeaker:"; } }
		public static string Love_hotel { get { return ":love_hotel:"; } }
		public static string Love_letter { get { return ":love_letter:"; } }
		public static string Low_brightness { get { return ":low_brightness:"; } }
		public static string M { get { return ":m:"; } }
		public static string Mag { get { return ":mag:"; } }
		public static string Mag_right { get { return ":mag_right:"; } }
		public static string Mahjong { get { return ":mahjong:"; } }
		public static string Mailbox { get { return ":mailbox:"; } }
		public static string Mailbox_closed { get { return ":mailbox_closed:"; } }
		public static string Mailbox_with_mail { get { return ":mailbox_with_mail:"; } }
		public static string Mailbox_with_no_mail { get { return ":mailbox_with_no_mail:"; } }
		public static string Man { get { return ":man:"; } }
		public static string Man_with_gua_pi_mao { get { return ":man_with_gua_pi_mao:"; } }
		public static string Man_with_turban { get { return ":man_with_turban:"; } }
		public static string Mans_shoe { get { return ":mans_shoe:"; } }
		public static string Maple_leaf { get { return ":maple_leaf:"; } }
		public static string Mask { get { return ":mask:"; } }
		public static string Massage { get { return ":massage:"; } }
		public static string Meat_on_bone { get { return ":meat_on_bone:"; } }
		public static string Mega { get { return ":mega:"; } }
		public static string Melon { get { return ":melon:"; } }
		public static string Memo { get { return ":memo:"; } }
		public static string Mens { get { return ":mens:"; } }
		public static string Metal { get { return ":metal:"; } }
		public static string Metro { get { return ":metro:"; } }
		public static string Microphone { get { return ":microphone:"; } }
		public static string Microscope { get { return ":microscope:"; } }
		public static string Milky_way { get { return ":milky_way:"; } }
		public static string Minibus { get { return ":minibus:"; } }
		public static string Minidisc { get { return ":minidisc:"; } }
		public static string Mobile_phone_off { get { return ":mobile_phone_off:"; } }
		public static string Money_with_wings { get { return ":money_with_wings:"; } }
		public static string Moneybag { get { return ":moneybag:"; } }
		public static string Monkey { get { return ":monkey:"; } }
		public static string Monkey_face { get { return ":monkey_face:"; } }
		public static string Monorail { get { return ":monorail:"; } }
		public static string Moon { get { return ":moon:"; } }
		public static string Mortar_board { get { return ":mortar_board:"; } }
		public static string Mount_fuji { get { return ":mount_fuji:"; } }
		public static string Mountain_bicyclist { get { return ":mountain_bicyclist:"; } }
		public static string Mountain_cableway { get { return ":mountain_cableway:"; } }
		public static string Mountain_railway { get { return ":mountain_railway:"; } }
		public static string Mouse { get { return ":mouse:"; } }
		public static string Mouse2 { get { return ":mouse2:"; } }
		public static string Movie_camera { get { return ":movie_camera:"; } }
		public static string Moyai { get { return ":moyai:"; } }
		public static string Muscle { get { return ":muscle:"; } }
		public static string Mushroom { get { return ":mushroom:"; } }
		public static string Musical_keyboard { get { return ":musical_keyboard:"; } }
		public static string Musical_note { get { return ":musical_note:"; } }
		public static string Musical_score { get { return ":musical_score:"; } }
		public static string Mute { get { return ":mute:"; } }
		public static string Nail_care { get { return ":nail_care:"; } }
		public static string Name_badge { get { return ":name_badge:"; } }
		public static string Neckbeard { get { return ":neckbeard:"; } }
		public static string Necktie { get { return ":necktie:"; } }
		public static string Negative_squared_cross_mark { get { return ":negative_squared_cross_mark:"; } }
		public static string Neutral_face { get { return ":neutral_face:"; } }
		public static string New { get { return ":new:"; } }
		public static string New_moon { get { return ":new_moon:"; } }
		public static string New_moon_with_face { get { return ":new_moon_with_face:"; } }
		public static string Newspaper { get { return ":newspaper:"; } }
		public static string Ng { get { return ":ng:"; } }
		public static string Nine { get { return ":nine:"; } }
		public static string No_bell { get { return ":no_bell:"; } }
		public static string No_bicycles { get { return ":no_bicycles:"; } }
		public static string No_entry { get { return ":no_entry:"; } }
		public static string No_entry_sign { get { return ":no_entry_sign:"; } }
		public static string No_good { get { return ":no_good:"; } }
		public static string No_mobile_phones { get { return ":no_mobile_phones:"; } }
		public static string No_mouth { get { return ":no_mouth:"; } }
		public static string No_pedestrians { get { return ":no_pedestrians:"; } }
		public static string No_smoking { get { return ":no_smoking:"; } }
		public static string Nonpotablewater { get { return ":non-potable_water:"; } }
		public static string Nose { get { return ":nose:"; } }
		public static string Notebook { get { return ":notebook:"; } }
		public static string Notebook_with_decorative_cover { get { return ":notebook_with_decorative_cover:"; } }
		public static string Notes { get { return ":notes:"; } }
		public static string Nut_and_bolt { get { return ":nut_and_bolt:"; } }
		public static string O { get { return ":o:"; } }
		public static string O2 { get { return ":o2:"; } }
		public static string Ocean { get { return ":ocean:"; } }
		public static string Octocat { get { return ":octocat:"; } }
		public static string Octopus { get { return ":octopus:"; } }
		public static string Oden { get { return ":oden:"; } }
		public static string Office { get { return ":office:"; } }
		public static string Ok { get { return ":ok:"; } }
		public static string Ok_hand { get { return ":ok_hand:"; } }
		public static string Ok_woman { get { return ":ok_woman:"; } }
		public static string Older_man { get { return ":older_man:"; } }
		public static string Older_woman { get { return ":older_woman:"; } }
		public static string On { get { return ":on:"; } }
		public static string Oncoming_automobile { get { return ":oncoming_automobile:"; } }
		public static string Oncoming_bus { get { return ":oncoming_bus:"; } }
		public static string Oncoming_police_car { get { return ":oncoming_police_car:"; } }
		public static string Oncoming_taxi { get { return ":oncoming_taxi:"; } }
		public static string One { get { return ":one:"; } }
		public static string Open_file_folder { get { return ":open_file_folder:"; } }
		public static string Open_hands { get { return ":open_hands:"; } }
		public static string Open_mouth { get { return ":open_mouth:"; } }
		public static string Ophiuchus { get { return ":ophiuchus:"; } }
		public static string Orange_book { get { return ":orange_book:"; } }
		public static string Outbox_tray { get { return ":outbox_tray:"; } }
		public static string Ox { get { return ":ox:"; } }
		public static string Package { get { return ":package:"; } }
		public static string Page_facing_up { get { return ":page_facing_up:"; } }
		public static string Page_with_curl { get { return ":page_with_curl:"; } }
		public static string Pager { get { return ":pager:"; } }
		public static string Palm_tree { get { return ":palm_tree:"; } }
		public static string Panda_face { get { return ":panda_face:"; } }
		public static string Paperclip { get { return ":paperclip:"; } }
		public static string Parking { get { return ":parking:"; } }
		public static string Part_alternation_mark { get { return ":part_alternation_mark:"; } }
		public static string Partly_sunny { get { return ":partly_sunny:"; } }
		public static string Passport_control { get { return ":passport_control:"; } }
		public static string Paw_prints { get { return ":paw_prints:"; } }
		public static string Peach { get { return ":peach:"; } }
		public static string Pear { get { return ":pear:"; } }
		public static string Pencil { get { return ":pencil:"; } }
		public static string Pencil2 { get { return ":pencil2:"; } }
		public static string Penguin { get { return ":penguin:"; } }
		public static string Pensive { get { return ":pensive:"; } }
		public static string Performing_arts { get { return ":performing_arts:"; } }
		public static string Persevere { get { return ":persevere:"; } }
		public static string Person_frowning { get { return ":person_frowning:"; } }
		public static string Person_with_blond_hair { get { return ":person_with_blond_hair:"; } }
		public static string Person_with_pouting_face { get { return ":person_with_pouting_face:"; } }
		public static string Phone { get { return ":phone:"; } }
		public static string Pig { get { return ":pig:"; } }
		public static string Pig2 { get { return ":pig2:"; } }
		public static string Pig_nose { get { return ":pig_nose:"; } }
		public static string Pill { get { return ":pill:"; } }
		public static string Pineapple { get { return ":pineapple:"; } }
		public static string Pisces { get { return ":pisces:"; } }
		public static string Pizza { get { return ":pizza:"; } }
		public static string Plus1 { get { return ":plus1:"; } }
		public static string Point_down { get { return ":point_down:"; } }
		public static string Point_left { get { return ":point_left:"; } }
		public static string Point_right { get { return ":point_right:"; } }
		public static string Point_up { get { return ":point_up:"; } }
		public static string Point_up_2 { get { return ":point_up_2:"; } }
		public static string Police_car { get { return ":police_car:"; } }
		public static string Poodle { get { return ":poodle:"; } }
		public static string Poop { get { return ":poop:"; } }
		public static string Post_office { get { return ":post_office:"; } }
		public static string Postal_horn { get { return ":postal_horn:"; } }
		public static string Postbox { get { return ":postbox:"; } }
		public static string Potable_water { get { return ":potable_water:"; } }
		public static string Pouch { get { return ":pouch:"; } }
		public static string Poultry_leg { get { return ":poultry_leg:"; } }
		public static string Pound { get { return ":pound:"; } }
		public static string Pouting_cat { get { return ":pouting_cat:"; } }
		public static string Pray { get { return ":pray:"; } }
		public static string Princess { get { return ":princess:"; } }
		public static string Punch { get { return ":punch:"; } }
		public static string Purple_heart { get { return ":purple_heart:"; } }
		public static string Purse { get { return ":purse:"; } }
		public static string Pushpin { get { return ":pushpin:"; } }
		public static string Put_litter_in_its_place { get { return ":put_litter_in_its_place:"; } }
		public static string Question { get { return ":question:"; } }
		public static string Rabbit { get { return ":rabbit:"; } }
		public static string Rabbit2 { get { return ":rabbit2:"; } }
		public static string Racehorse { get { return ":racehorse:"; } }
		public static string Radio { get { return ":radio:"; } }
		public static string Radio_button { get { return ":radio_button:"; } }
		public static string Rage { get { return ":rage:"; } }
		public static string Rage1 { get { return ":rage1:"; } }
		public static string Rage2 { get { return ":rage2:"; } }
		public static string Rage3 { get { return ":rage3:"; } }
		public static string Rage4 { get { return ":rage4:"; } }
		public static string Railway_car { get { return ":railway_car:"; } }
		public static string Rainbow { get { return ":rainbow:"; } }
		public static string Raised_hand { get { return ":raised_hand:"; } }
		public static string Raised_hands { get { return ":raised_hands:"; } }
		public static string Raising_hand { get { return ":raising_hand:"; } }
		public static string Ram { get { return ":ram:"; } }
		public static string Ramen { get { return ":ramen:"; } }
		public static string Rat { get { return ":rat:"; } }
		public static string Recycle { get { return ":recycle:"; } }
		public static string Red_car { get { return ":red_car:"; } }
		public static string Red_circle { get { return ":red_circle:"; } }
		public static string Registered { get { return ":registered:"; } }
		public static string Relaxed { get { return ":relaxed:"; } }
		public static string Relieved { get { return ":relieved:"; } }
		public static string Repeat { get { return ":repeat:"; } }
		public static string Repeat_one { get { return ":repeat_one:"; } }
		public static string Restroom { get { return ":restroom:"; } }
		public static string Revolving_hearts { get { return ":revolving_hearts:"; } }
		public static string Rewind { get { return ":rewind:"; } }
		public static string Ribbon { get { return ":ribbon:"; } }
		public static string Rice { get { return ":rice:"; } }
		public static string Rice_ball { get { return ":rice_ball:"; } }
		public static string Rice_cracker { get { return ":rice_cracker:"; } }
		public static string Rice_scene { get { return ":rice_scene:"; } }
		public static string Ring { get { return ":ring:"; } }
		public static string Rocket { get { return ":rocket:"; } }
		public static string Roller_coaster { get { return ":roller_coaster:"; } }
		public static string Rooster { get { return ":rooster:"; } }
		public static string Rose { get { return ":rose:"; } }
		public static string Rotating_light { get { return ":rotating_light:"; } }
		public static string Round_pushpin { get { return ":round_pushpin:"; } }
		public static string Rowboat { get { return ":rowboat:"; } }
		public static string Ru { get { return ":ru:"; } }
		public static string Rugby_football { get { return ":rugby_football:"; } }
		public static string Runner { get { return ":runner:"; } }
		public static string Running { get { return ":running:"; } }
		public static string Running_shirt_with_sash { get { return ":running_shirt_with_sash:"; } }
		public static string Sa { get { return ":sa:"; } }
		public static string Sagittarius { get { return ":sagittarius:"; } }
		public static string Sailboat { get { return ":sailboat:"; } }
		public static string Sake { get { return ":sake:"; } }
		public static string Sandal { get { return ":sandal:"; } }
		public static string Santa { get { return ":santa:"; } }
		public static string Satellite { get { return ":satellite:"; } }
		public static string Satisfied { get { return ":satisfied:"; } }
		public static string Saxophone { get { return ":saxophone:"; } }
		public static string School { get { return ":school:"; } }
		public static string School_satchel { get { return ":school_satchel:"; } }
		public static string Scissors { get { return ":scissors:"; } }
		public static string Scorpius { get { return ":scorpius:"; } }
		public static string Scream { get { return ":scream:"; } }
		public static string Scream_cat { get { return ":scream_cat:"; } }
		public static string Scroll { get { return ":scroll:"; } }
		public static string Seat { get { return ":seat:"; } }
		public static string Secret { get { return ":secret:"; } }
		public static string See_no_evil { get { return ":see_no_evil:"; } }
		public static string Seedling { get { return ":seedling:"; } }
		public static string Seven { get { return ":seven:"; } }
		public static string Shaved_ice { get { return ":shaved_ice:"; } }
		public static string Sheep { get { return ":sheep:"; } }
		public static string Shell { get { return ":shell:"; } }
		public static string Ship { get { return ":ship:"; } }
		public static string Shipit { get { return ":shipit:"; } }
		public static string Shirt { get { return ":shirt:"; } }
		public static string Shit { get { return ":shit:"; } }
		public static string Shoe { get { return ":shoe:"; } }
		public static string Shower { get { return ":shower:"; } }
		public static string Signal_strength { get { return ":signal_strength:"; } }
		public static string Six { get { return ":six:"; } }
		public static string Six_pointed_star { get { return ":six_pointed_star:"; } }
		public static string Ski { get { return ":ski:"; } }
		public static string Skull { get { return ":skull:"; } }
		public static string Sleeping { get { return ":sleeping:"; } }
		public static string Sleepy { get { return ":sleepy:"; } }
		public static string Slot_machine { get { return ":slot_machine:"; } }
		public static string Small_blue_diamond { get { return ":small_blue_diamond:"; } }
		public static string Small_orange_diamond { get { return ":small_orange_diamond:"; } }
		public static string Small_red_triangle { get { return ":small_red_triangle:"; } }
		public static string Small_red_triangle_down { get { return ":small_red_triangle_down:"; } }
		public static string Smile { get { return ":smile:"; } }
		public static string Smile_cat { get { return ":smile_cat:"; } }
		public static string Smiley { get { return ":smiley:"; } }
		public static string Smiley_cat { get { return ":smiley_cat:"; } }
		public static string Smiling_imp { get { return ":smiling_imp:"; } }
		public static string Smirk { get { return ":smirk:"; } }
		public static string Smirk_cat { get { return ":smirk_cat:"; } }
		public static string Smoking { get { return ":smoking:"; } }
		public static string Snail { get { return ":snail:"; } }
		public static string Snake { get { return ":snake:"; } }
		public static string Snowboarder { get { return ":snowboarder:"; } }
		public static string Snowflake { get { return ":snowflake:"; } }
		public static string Snowman { get { return ":snowman:"; } }
		public static string Sob { get { return ":sob:"; } }
		public static string Soccer { get { return ":soccer:"; } }
		public static string Soon { get { return ":soon:"; } }
		public static string Sos { get { return ":sos:"; } }
		public static string Sound { get { return ":sound:"; } }
		public static string Space_invader { get { return ":space_invader:"; } }
		public static string Spades { get { return ":spades:"; } }
		public static string Spaghetti { get { return ":spaghetti:"; } }
		public static string Sparkle { get { return ":sparkle:"; } }
		public static string Sparkler { get { return ":sparkler:"; } }
		public static string Sparkles { get { return ":sparkles:"; } }
		public static string Sparkling_heart { get { return ":sparkling_heart:"; } }
		public static string Speak_no_evil { get { return ":speak_no_evil:"; } }
		public static string Speaker { get { return ":speaker:"; } }
		public static string Speech_balloon { get { return ":speech_balloon:"; } }
		public static string Speedboat { get { return ":speedboat:"; } }
		public static string Squirrel { get { return ":squirrel:"; } }
		public static string Star { get { return ":star:"; } }
		public static string Star2 { get { return ":star2:"; } }
		public static string Stars { get { return ":stars:"; } }
		public static string Station { get { return ":station:"; } }
		public static string Statue_of_liberty { get { return ":statue_of_liberty:"; } }
		public static string Steam_locomotive { get { return ":steam_locomotive:"; } }
		public static string Stew { get { return ":stew:"; } }
		public static string Straight_ruler { get { return ":straight_ruler:"; } }
		public static string Strawberry { get { return ":strawberry:"; } }
		public static string Stuck_out_tongue { get { return ":stuck_out_tongue:"; } }
		public static string Stuck_out_tongue_closed_eyes { get { return ":stuck_out_tongue_closed_eyes:"; } }
		public static string Stuck_out_tongue_winking_eye { get { return ":stuck_out_tongue_winking_eye:"; } }
		public static string Sun_with_face { get { return ":sun_with_face:"; } }
		public static string Sunflower { get { return ":sunflower:"; } }
		public static string Sunglasses { get { return ":sunglasses:"; } }
		public static string Sunny { get { return ":sunny:"; } }
		public static string Sunrise { get { return ":sunrise:"; } }
		public static string Sunrise_over_mountains { get { return ":sunrise_over_mountains:"; } }
		public static string Surfer { get { return ":surfer:"; } }
		public static string Sushi { get { return ":sushi:"; } }
		public static string Suspect { get { return ":suspect:"; } }
		public static string Suspension_railway { get { return ":suspension_railway:"; } }
		public static string Sweat { get { return ":sweat:"; } }
		public static string Sweat_drops { get { return ":sweat_drops:"; } }
		public static string Sweat_smile { get { return ":sweat_smile:"; } }
		public static string Sweet_potato { get { return ":sweet_potato:"; } }
		public static string Swimmer { get { return ":swimmer:"; } }
		public static string Symbols { get { return ":symbols:"; } }
		public static string Syringe { get { return ":syringe:"; } }
		public static string Tada { get { return ":tada:"; } }
		public static string Tanabata_tree { get { return ":tanabata_tree:"; } }
		public static string Tangerine { get { return ":tangerine:"; } }
		public static string Taurus { get { return ":taurus:"; } }
		public static string Taxi { get { return ":taxi:"; } }
		public static string Tea { get { return ":tea:"; } }
		public static string Telephone { get { return ":telephone:"; } }
		public static string Telephone_receiver { get { return ":telephone_receiver:"; } }
		public static string Telescope { get { return ":telescope:"; } }
		public static string Tennis { get { return ":tennis:"; } }
		public static string Tent { get { return ":tent:"; } }
		public static string Thought_balloon { get { return ":thought_balloon:"; } }
		public static string Three { get { return ":three:"; } }
		public static string Thumbsdown { get { return ":thumbsdown:"; } }
		public static string Thumbsup { get { return ":thumbsup:"; } }
		public static string Ticket { get { return ":ticket:"; } }
		public static string Tiger { get { return ":tiger:"; } }
		public static string Tiger2 { get { return ":tiger2:"; } }
		public static string Tired_face { get { return ":tired_face:"; } }
		public static string Tm { get { return ":tm:"; } }
		public static string Toilet { get { return ":toilet:"; } }
		public static string Tokyo_tower { get { return ":tokyo_tower:"; } }
		public static string Tomato { get { return ":tomato:"; } }
		public static string Tongue { get { return ":tongue:"; } }
		public static string Top { get { return ":top:"; } }
		public static string Tophat { get { return ":tophat:"; } }
		public static string Tractor { get { return ":tractor:"; } }
		public static string Traffic_light { get { return ":traffic_light:"; } }
		public static string Train { get { return ":train:"; } }
		public static string Train2 { get { return ":train2:"; } }
		public static string Tram { get { return ":tram:"; } }
		public static string Triangular_flag_on_post { get { return ":triangular_flag_on_post:"; } }
		public static string Triangular_ruler { get { return ":triangular_ruler:"; } }
		public static string Trident { get { return ":trident:"; } }
		public static string Triumph { get { return ":triumph:"; } }
		public static string Trolleybus { get { return ":trolleybus:"; } }
		public static string Trollface { get { return ":trollface:"; } }
		public static string Trophy { get { return ":trophy:"; } }
		public static string Tropical_drink { get { return ":tropical_drink:"; } }
		public static string Tropical_fish { get { return ":tropical_fish:"; } }
		public static string Truck { get { return ":truck:"; } }
		public static string Trumpet { get { return ":trumpet:"; } }
		public static string Tshirt { get { return ":tshirt:"; } }
		public static string Tulip { get { return ":tulip:"; } }
		public static string Turtle { get { return ":turtle:"; } }
		public static string Tv { get { return ":tv:"; } }
		public static string Twisted_rightwards_arrows { get { return ":twisted_rightwards_arrows:"; } }
		public static string Two { get { return ":two:"; } }
		public static string Two_hearts { get { return ":two_hearts:"; } }
		public static string Two_men_holding_hands { get { return ":two_men_holding_hands:"; } }
		public static string Two_women_holding_hands { get { return ":two_women_holding_hands:"; } }
		public static string U5272 { get { return ":u5272:"; } }
		public static string U5408 { get { return ":u5408:"; } }
		public static string U55b6 { get { return ":u55b6:"; } }
		public static string U6307 { get { return ":u6307:"; } }
		public static string U6708 { get { return ":u6708:"; } }
		public static string U6709 { get { return ":u6709:"; } }
		public static string U6e80 { get { return ":u6e80:"; } }
		public static string U7121 { get { return ":u7121:"; } }
		public static string U7533 { get { return ":u7533:"; } }
		public static string U7981 { get { return ":u7981:"; } }
		public static string U7a7a { get { return ":u7a7a:"; } }
		public static string Uk { get { return ":uk:"; } }
		public static string Umbrella { get { return ":umbrella:"; } }
		public static string Unamused { get { return ":unamused:"; } }
		public static string Underage { get { return ":underage:"; } }
		public static string Unlock { get { return ":unlock:"; } }
		public static string Up { get { return ":up:"; } }
		public static string Us { get { return ":us:"; } }
		public static string V { get { return ":v:"; } }
		public static string Vertical_traffic_light { get { return ":vertical_traffic_light:"; } }
		public static string Vhs { get { return ":vhs:"; } }
		public static string Vibration_mode { get { return ":vibration_mode:"; } }
		public static string Video_camera { get { return ":video_camera:"; } }
		public static string Video_game { get { return ":video_game:"; } }
		public static string Violin { get { return ":violin:"; } }
		public static string Virgo { get { return ":virgo:"; } }
		public static string Volcano { get { return ":volcano:"; } }
		public static string Vs { get { return ":vs:"; } }
		public static string Walking { get { return ":walking:"; } }
		public static string Waning_crescent_moon { get { return ":waning_crescent_moon:"; } }
		public static string Waning_gibbous_moon { get { return ":waning_gibbous_moon:"; } }
		public static string Warning { get { return ":warning:"; } }
		public static string Watch { get { return ":watch:"; } }
		public static string Water_buffalo { get { return ":water_buffalo:"; } }
		public static string Watermelon { get { return ":watermelon:"; } }
		public static string Wave { get { return ":wave:"; } }
		public static string Wavy_dash { get { return ":wavy_dash:"; } }
		public static string Waxing_crescent_moon { get { return ":waxing_crescent_moon:"; } }
		public static string Waxing_gibbous_moon { get { return ":waxing_gibbous_moon:"; } }
		public static string Wc { get { return ":wc:"; } }
		public static string Weary { get { return ":weary:"; } }
		public static string Wedding { get { return ":wedding:"; } }
		public static string Whale { get { return ":whale:"; } }
		public static string Whale2 { get { return ":whale2:"; } }
		public static string Wheelchair { get { return ":wheelchair:"; } }
		public static string White_check_mark { get { return ":white_check_mark:"; } }
		public static string White_circle { get { return ":white_circle:"; } }
		public static string White_flower { get { return ":white_flower:"; } }
		public static string White_large_square { get { return ":white_large_square:"; } }
		public static string White_medium_small_square { get { return ":white_medium_small_square:"; } }
		public static string White_medium_square { get { return ":white_medium_square:"; } }
		public static string White_small_square { get { return ":white_small_square:"; } }
		public static string White_square_button { get { return ":white_square_button:"; } }
		public static string Wind_chime { get { return ":wind_chime:"; } }
		public static string Wine_glass { get { return ":wine_glass:"; } }
		public static string Wink { get { return ":wink:"; } }
		public static string Wolf { get { return ":wolf:"; } }
		public static string Woman { get { return ":woman:"; } }
		public static string Womans_clothes { get { return ":womans_clothes:"; } }
		public static string Womans_hat { get { return ":womans_hat:"; } }
		public static string Womens { get { return ":womens:"; } }
		public static string Worried { get { return ":worried:"; } }
		public static string Wrench { get { return ":wrench:"; } }
		public static string X { get { return ":x:"; } }
		public static string Yellow_heart { get { return ":yellow_heart:"; } }
		public static string Yen { get { return ":yen:"; } }
		public static string Yum { get { return ":yum:"; } }
		public static string Zap { get { return ":zap:"; } }
		public static string Zero { get { return ":zero:"; } }
		public static string Zzz { get { return ":zzz:"; } }

	}
}