name: Continuous Stuff
on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - master
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    name: Dotnet build
    steps:
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow
      - run: |
          git branch master origin/master
        if: github.event_name != 'push' || (github.event_name == 'push' && github.ref != 'refs/heads/master')
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "2.2.103"
      - name: Build
        run: .\build.ps1
        shell: pwsh
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NugetKey }}
      - name: Add artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ steps.build.outputs.nupkg_name }}
          path: ${{ steps.build.outputs.nupkg }}
