name: Continuous Stuff
on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - master
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet build
    steps:
      - uses: actions/checkout@v2
      - run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' src/.nuget.config > src/nuget.config
      - run: dotnet build src/ -c Release --nologo
      - run: dotnet test src/ -c Release --no-build --nologo
      - run: |
          cd src/
          dotnet nuget push "Slack.Webhooks/bin/Release/*.nupkg" --source "github"
