name: Continuous Stuff
on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - master
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Inject GITHUB_TOKEN
        run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' src/.nuget.config > src/nuget.config
      - name: Restore
        run: dotnet restore src/ -s nuget
      - name: Build
        run: dotnet build src/ -c Release --nologo
      - name: Test
        run: dotnet test src/ -c Release --no-build --nologo
      - name: Push
        run: |
          cd src/
          dotnet nuget push "Slack.Webhooks/bin/Release/*.nupkg" --source "github"
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1