name: Continuous Stuff
on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - master
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet build
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: dotnet build -c Release --nologo
      - name: Run Unit Tests
        run: dotnet test -c Release --no-build --nologo
      - name: Push to Feedz.io
        run: dotnet nuget push "src/Slack.Webhooks/bin/Release/*.nupkg" --source "https://f.feedz.io/mrb0nj/slack-webhooks/nuget/index.json" -k ${{ secrets.FEEDZIO_TOKEN }} -n true
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v'))
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1