name: Continuous Stuff
on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - master
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet build
    steps:
      - uses: actions/checkout@v2
      - run: cd src
      - run: sed 's/GITHUB_TOKEN/${{ secrets.GITHUB_TOKEN }}/g' .nuget.config > nuget.config
      - run: dotnet build -c Release --nologo
      - run: dotnet test -c Release --no-build --nologo
      - run: dotnet nuget push "Slack.Webhooks/bin/Release/*.nupkg" --source "github"
