name: Continuous Stuff
on:
  push:
    branches:
      - feature/*
      - hotfix/*
      - master
    tags:
      - v*
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet build
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.100"
      - run: dotnet build src/ -c Release --nologo
      - run: dotnet test src/ -c Release --no-build --nologo
      - run: dotnet nuget push "src/Slack.Webhooks\bin\Release\*.nupkg" --source "github"
